namespace Xmpp.Im
{
    /// <summary>
    /// Defines the possible types for Message stanzas.
    /// </summary>
    public enum MessageType
    {
        /// <summary>
        /// The XmppMessage is a single XmppMessage that is sent outside the context of
        /// a one-to-one conversation or groupchat.
        /// </summary>
        Normal,

        /// <summary>
        /// The XmppMessage is sent in the context of a one-to-one chat conversation.
        /// </summary>
        Chat,

        /// <summary>
        /// An error has occurred related to a previous XmppMessage sent by the sender.
        /// </summary>
        Error,

        /// <summary>
        /// The XmppMessage is sent in the context of a multi-user chat environment.
        /// </summary>
        Groupchat,

        /// <summary>
        /// The XmppMessage is generated by an automated service that delivers or
        /// broadcasts content.
        /// </summary>
        Headline
    }
}